
version: '3.8'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./uploads:/usr/src/app/uploads
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
